name: Daily Instagram Insights Collector

# 언제 이 워크플로우를 실행할지 정의
on:
  schedule:
    # cron 스케줄 표현식: '분 시 일 월 요일'
    # 매일 UTC 기준 17:00 (한국 시간 새벽 2시)에 실행
    - cron: '0 17 * * *'
  # Actions 탭에서 수동으로 실행할 수 있도록 버튼 추가
  workflow_dispatch:

# 실행할 작업(Job) 정의
jobs:
  build:
    # '우분투'라는 리눅스 가상 컴퓨터에서 실행
    runs-on: ubuntu-latest

    # 작업 단계(Step) 정의
    steps:
      # 1. 레포지토리의 코드를 가상 컴퓨터로 다운로드
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 파이썬 3.10 버전 설치
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 필요한 파이썬 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests supabase python-dotenv

      # 4. 우리의 파이썬 스크립트 실행
      - name: Run Python script
        # GitHub Secrets에 등록한 비밀 정보들을 '환경 변수'로 주입
        env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          IG_ACCOUNT_ID: ${{ secrets.IG_ACCOUNT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python insights_data.py # 스크립트 파일 이름